module.exports = {
  TEST_USERNAME: "admin",
  TEST_PASSWORD: "password",
  CONCURRENT_USERS_COUNT: 100,
  MEMORY_USAGE_REQUESTS: 50,
  CONCURRENT_USER_CREATION_COUNT: 20,
  ENDPOINT_STRESS_TEST_REQUESTS: 500,
  BRUTE_FORCE_ATTEMPTS: 50,
  LARGE_DATA_PAYLOAD_SIZE: 1024 * 500,
  RESOURCE_EXHAUSTION_OPERATIONS: 30,
  AUTH_MAX_ATTEMPTS: 1000,
  AUTH_COOLDOWN_TIME: 15 * 60 * 1000
};
