export const HELLO_ENDPOINT = "/api/v1/hello";
export const HEALTH_ENDPOINT = "/api/v1/health";
export const HEALTH_FULL_ENDPOINT = "/api/v1/health/full";
export const RESET_LOGIN_ATTEMPTS_ENDPOINT = "/api/v1/meta/reset-login-attempts";
export const RESET_TEST_STATE_ENDPOINT = "/api/v1/meta/reset-test-state";
export const RUN_BRUTE_FORCE_TEST_ENDPOINT = "/api/v1/meta/run-brute-force-test";
export const LOG_SIZE_ENDPOINT = "/api/v1/meta/log-size";
export const CLEANUP_USER_ENDPOINT = "/api/v1/meta/cleanup-user/:id";
export const CLEANUP_DATA_ENDPOINT = "/api/v1/meta/cleanup-data/:id";
export const TEST_ERROR_ENDPOINT = "/api/v1/meta/test-error";
export const SHUTDOWN_ENDPOINT = "/api/v1/shut";
export const LOGS_ENDPOINT = "/api/v1/logs";
export const HELLO_MESSAGE = "here da data.";
export const HEALTH_STATUS_MESSAGE = "online";
export const HEALTH_FULL_ERROR_MESSAGE = "Failed to get full health status";
export const RESET_LOGIN_ATTEMPTS_MESSAGE = "Login attempts reset successfully";
export const RESET_TEST_STATE_MESSAGE = "Test state reset successfully";
export const BRUTE_FORCE_FAILED_MESSAGE = "Failed to run brute-force test server-side";
export const LOG_SIZE_ERROR_MESSAGE = "Failed to get log file size";
export const USER_CLEANUP_SUCCESS_MESSAGE = (userId) => `User ${userId} cleaned up successfully.`;
export const USER_CLEANUP_NOT_FOUND_MESSAGE = (userId) => `User ${userId} not found, already cleaned up or never existed.`;
export const DATA_CLEANUP_SUCCESS_MESSAGE = (dataId) => `Data ${dataId} cleaned up successfully.`;
export const DATA_CLEANUP_NOT_FOUND_MESSAGE = (dataId) => `Data ${dataId} not found, already cleaned up or never existed.`;
export const TEST_ERROR_MESSAGE = "This is a test error from /api/v1/meta/test-error";
export const SHUTDOWN_TEST_SUCCESS_MESSAGE = "shutdown test successful - system would shut down in production.";
export const SHUTDOWN_INITIATED_MESSAGE = "shutdown initiated.";
export const SHUTDOWN_COMMAND_FAILED_MESSAGE = "Shutdown command failed:";
export const SHUTDOWN_INITIATED_LOG_MESSAGE = "Shutdown initiated - system will shut down in 5 seconds";
export const LOG_READ_ERROR_MESSAGE = "Failed to read logs";
export const LOG_CLEAR_SUCCESS_MESSAGE = "Log file cleared successfully";
export const LOG_CLEAR_ERROR_MESSAGE = "Failed to clear log file";
export const BRUTE_FORCE_ATTEMPTS_COUNT = 5;
export const BRUTE_FORCE_USERNAME = 'invalid_user';
export const BRUTE_FORCE_PASSWORD = 'wrong_password';
export const BRUTE_FORCE_HOSTNAME = 'localhost';
export const BRUTE_FORCE_PORT = 8000;
export const BRUTE_FORCE_AUTH_PATH = '/api/v1/auth';
export const BRUTE_FORCE_UNAUTHORIZED_STATUS = 401;
export const SHUTDOWN_COMMAND = "shutdown /s /t 5";
export const SHUTDOWN_DELAY_MS = 1000;
