export const AUTH_COOKIE_NAME = "authenticated";
export const ACCESS_DENIED_MESSAGE = "access denied: need to be authenticated.";
export const LOGIN_ENDPOINT = "/api/v1/login";
export const LOGOUT_ENDPOINT = "/api/v1/logout";
export const AUTH_POST_ENDPOINT = "/api/v1/auth";
export const LOGIN_REDIRECT_PATH = "/";
export const LOGOUT_REDIRECT_PATH = "/";
export const ADMIN_USERNAME = "admin";
export const ADMIN_PASSWORD = "password";
export const USERNAME_PASSWORD_REQUIRED_MESSAGE = "Username and password are required";
export const AUTHENTICATION_SUCCESS_MESSAGE = "Authentication successful";
export const INVALID_CREDENTIALS_MESSAGE = "Invalid credentials";
export const RATE_LIMIT_EXCEEDED_MESSAGE = "Too many login attempts. Please try again later.";
export const IP_RESET_LOG_MESSAGE = (ip) => `Login attempts for IP ${ip} reset.`;
export const ALL_RESET_LOG_MESSAGE = "All login attempts reset.";
