module.exports = {
  HELLO_ENDPOINT: "/api/v1/hello",
  HEALTH_ENDPOINT: "/api/v1/health",
  HEALTH_FULL_ENDPOINT: "/api/v1/health/full",
  RESET_LOGIN_ATTEMPTS_ENDPOINT: "/api/v1/meta/reset-login-attempts",
  RESET_TEST_STATE_ENDPOINT: "/api/v1/meta/reset-test-state",
  RUN_BRUTE_FORCE_TEST_ENDPOINT: "/api/v1/meta/run-brute-force-test",
  LOG_SIZE_ENDPOINT: "/api/v1/meta/log-size",
  CLEANUP_USER_ENDPOINT: "/api/v1/meta/cleanup-user/:id",
  CLEANUP_DATA_ENDPOINT: "/api/v1/meta/cleanup-data/:id",
  TEST_ERROR_ENDPOINT: "/api/v1/meta/test-error",
  SHUTDOWN_ENDPOINT: "/api/v1/shut",
  LOGS_ENDPOINT: "/api/v1/logs",
  HELLO_MESSAGE: "here da data.",
  HEALTH_STATUS_MESSAGE: "online",
  HEALTH_FULL_ERROR_MESSAGE: "Failed to get full health status",
  RESET_LOGIN_ATTEMPTS_MESSAGE: "Login attempts reset successfully",
  RESET_TEST_STATE_MESSAGE: "Test state reset successfully",
  BRUTE_FORCE_FAILED_MESSAGE: "Failed to run brute-force test server-side",
  LOG_SIZE_ERROR_MESSAGE: "Failed to get log file size",
  USER_CLEANUP_SUCCESS_MESSAGE: (userId) => `User ${userId} cleaned up successfully.`,
  USER_CLEANUP_NOT_FOUND_MESSAGE: (userId) => `User ${userId} not found, already cleaned up or never existed.`,
  DATA_CLEANUP_SUCCESS_MESSAGE: (dataId) => `Data ${dataId} cleaned up successfully.`,
  DATA_CLEANUP_NOT_FOUND_MESSAGE: (dataId) => `Data ${dataId} not found, already cleaned up or never existed.`,
  TEST_ERROR_MESSAGE: "This is a test error from /api/v1/meta/test-error",
  SHUTDOWN_TEST_SUCCESS_MESSAGE: "shutdown test successful - system would shut down in production.",
  SHUTDOWN_INITIATED_MESSAGE: "shutdown initiated.",
  SHUTDOWN_COMMAND_FAILED_MESSAGE: "Shutdown command failed:",
  SHUTDOWN_INITIATED_LOG_MESSAGE: "Shutdown initiated - system will shut down in 5 seconds",
  LOG_READ_ERROR_MESSAGE: "Failed to read logs",
  LOG_CLEAR_SUCCESS_MESSAGE: "Log file cleared successfully",
  LOG_CLEAR_ERROR_MESSAGE: "Failed to clear log file",
  BRUTE_FORCE_ATTEMPTS_COUNT: 5,
  BRUTE_FORCE_USERNAME: 'invalid_user',
  BRUTE_FORCE_PASSWORD: 'wrong_password',
  BRUTE_FORCE_HOSTNAME: 'localhost',
  BRUTE_FORCE_PORT: 8000,
  BRUTE_FORCE_AUTH_PATH: '/api/v1/auth',
  BRUTE_FORCE_UNAUTHORIZED_STATUS: 401,
  SHUTDOWN_COMMAND: "shutdown /s /t 5",
  SHUTDOWN_DELAY_MS: 1000,
};
