export const USERS_BASE_ENDPOINT = "/api/v1/users";
export const USERS_ID_ENDPOINT = "/api/v1/users/:id";
export const USERS_GET_ERROR_MESSAGE = "Failed to get users";
export const USER_NAME_EMAIL_REQUIRED_MESSAGE = "Name and email are required";
export const USER_CREATED_SUCCESS_MESSAGE = "User created successfully";
export const USER_CREATE_ERROR_MESSAGE = "Failed to create user";
export const USER_NOT_FOUND_MESSAGE = "User not found";
export const USER_UPDATED_SUCCESS_MESSAGE = "User updated successfully";
export const USER_DELETE_SUCCESS_MESSAGE = "User deleted successfully";
